import dotenv from "dotenv";
dotenv.config();

import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

let aiClient: GoogleGenAI | null = null;

function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    aiClient = new GoogleGenAI({ apiKey });
  }
  return aiClient;
}

async function startServer() {
  const app = express();
  const PORT = 3000;

  // JSON Body Parser with 50MB limit to handle base64 photos smoothly
  app.use(express.json({ limit: "50mb" }));
  app.use(express.urlencoded({ extended: true, limit: "50mb" }));

  // API Health Check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok" });
  });

  // POST /api/gemini/suggest-moment
  // Generates a short evocative phrase (<= 60 chars) and an intimate note from a photo
  app.post("/api/gemini/suggest-moment", async (req, res) => {
    try {
      const { mediaUrl, currentPhrase, cityName, countryName } = req.body;

      if (!mediaUrl || typeof mediaUrl !== "string") {
        return res.status(400).json({ error: "mediaUrl is required" });
      }

      const ai = getGeminiClient();

      let base64Data = "";
      let mimeType = "image/jpeg";

      // Case 1: Data URL (uploaded image in base64)
      if (mediaUrl.startsWith("data:")) {
        const matches = mediaUrl.match(/^data:([^;]+);base64,(.+)$/s);
        if (matches) {
          mimeType = matches[1];
          base64Data = matches[2];
        }
      }
      // Case 2: Remote HTTP/S URL (presets from Unsplash or remote storage)
      else if (mediaUrl.startsWith("http://") || mediaUrl.startsWith("https://")) {
        try {
          const imgResponse = await fetch(mediaUrl);
          if (imgResponse.ok) {
            const arrayBuffer = await imgResponse.arrayBuffer();
            base64Data = Buffer.from(arrayBuffer).toString("base64");
            const ct = imgResponse.headers.get("content-type");
            if (ct) mimeType = ct;
          }
        } catch (fetchErr) {
          console.warn("Could not download remote image for Gemini vision:", fetchErr);
        }
      }

      const promptContext = [
        "Eres el asistente poético, sensible y nostálgico de 'Momentos: Atlas Personal'.",
        "Tu misión es observar detenidamente la fotografía de un viaje y sugerir dos textos:",
        "1. 'phrase': Una frase corta y muy evocadora, de MÁXIMO 60 CARACTERES, en español, estilo diario de viaje íntimo o título conmovedor.",
        "2. 'note': Una descripción breve de 1 o 2 frases en español sobre lo que probablemente esté sucediendo o la atmósfera emocional de la imagen, con tono íntimo, cálido y nostálgico.",
        cityName ? `Lugar o ciudad: ${cityName}${countryName ? `, ${countryName}` : ""}.` : "",
        currentPhrase && currentPhrase.trim()
          ? `El usuario ya apuntó esto como contexto inicial: "${currentPhrase.trim()}". Tu sugerencia DEBE respetarlo y enriquecerlo en vez de ignorarlo.`
          : "El usuario aún no ha escrito nada. Inspírate libremente en la atmósfera, texturas, luz y sentimientos de la foto.",
      ]
        .filter(Boolean)
        .join("\n");

      const parts: any[] = [];
      if (base64Data) {
        parts.push({
          inlineData: {
            mimeType,
            data: base64Data,
          },
        });
      }
      parts.push({
        text: promptContext,
      });

      const response = await ai.models.generateContent({
        model: "gemini-3.8-flash",
        contents: { parts },
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              phrase: {
                type: Type.STRING,
                description:
                  "Frase corta y evocadora para el momento, máximo 60 caracteres, en español, estilo diario de viaje.",
              },
              note: {
                type: Type.STRING,
                description:
                  "Descripción breve de 1-2 frases sobre lo que probablemente esté pasando en la foto, en tono íntimo y nostálgico.",
              },
            },
            required: ["phrase", "note"],
          },
        },
      });

      const text = response.text;
      if (!text) {
        return res.status(500).json({ error: "No response text generated by Gemini" });
      }

      const parsed = JSON.parse(text);
      const cleanPhrase = (parsed.phrase || "").trim().slice(0, 60);
      const cleanNote = (parsed.note || "").trim();

      return res.json({
        phrase: cleanPhrase,
        note: cleanNote,
      });
    } catch (err: any) {
      console.error("Error in /api/gemini/suggest-moment:", err);
      return res.status(500).json({
        error: err?.message || "Failed to generate AI moment suggestion",
      });
    }
  });

  // Vite middleware in dev; static serving in production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
